# Generated by Django 5.0.7 on 2024-07-16 07:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_mst',
            name='product_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product_sub_cat',
            name='Product_sub_cat_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
